#import <Foundation/Foundation.h>
#import "SWGExercise.h"
#import "SWGUser.h"
#import "SWGObject.h"
#import "SWGApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SWGDefaultApi: NSObject

@property(nonatomic, assign)SWGApiClient *apiClient;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SWGDefaultApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SWGDefaultApi*) sharedAPI;
///
///
/// 
/// Getting a test
///
/// @param exerciseName Name of the exercise to fetch
/// 
///
/// @return SWGExercise*
-(NSNumber*) exerciseExerciseNameGetWithCompletionBlock :(NSString*) exerciseName 
    
    completionHandler: (void (^)(SWGExercise* output, NSError* error))completionBlock;
    


///
///
/// 
/// Getting the profile of this user in JSON
///
/// 
///
/// @return SWGUser*
-(NSNumber*) profileGetWithCompletionBlock :
    (void (^)(SWGUser* output, NSError* error))completionBlock;
    


///
///
/// 
/// 
///
/// 
///
/// @return NSString*
-(NSNumber*) testPostPostWithCompletionBlock :
    (void (^)(NSString* output, NSError* error))completionBlock;
    



@end
