#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGExam
@end

@interface SWGExam : SWGObject


@property(nonatomic) NSString* name;

@property(nonatomic) NSString* url;

@property(nonatomic) NSString* mediaUrl;

@property(nonatomic) NSNumber* allowedTime;

@property(nonatomic) NSNumber* requiredScore;

@property(nonatomic) NSNumber* numberOfQuestions;

@end
