#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGMaterial.h"


@protocol SWGExercise
@end

@interface SWGExercise : SWGObject


@property(nonatomic) NSString* exerciseType;

@property(nonatomic) NSArray<SWGMaterial>* materials;

@end
