#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGMaterial.h"


@protocol SWGMaterial
@end

@interface SWGMaterial : SWGObject


@property(nonatomic) NSString* id;

@property(nonatomic) NSString* seqType;

@property(nonatomic) NSString* exercise;

@property(nonatomic) NSNumber* exerciseId;

@property(nonatomic) NSString* parent;

@property(nonatomic) NSNumber* dropTargetId;

@property(nonatomic) SWGMaterial* dropTarget;

@property(nonatomic) NSArray<SWGMaterial>* dropElements;

@property(nonatomic) NSNumber* blobId;

@property(nonatomic) NSString* blob;

@property(nonatomic) NSNumber* handlingId;

@property(nonatomic) NSString* name;

@property(nonatomic) NSString* type;

@property(nonatomic) NSNumber* X;

@property(nonatomic) NSNumber* Y;

@property(nonatomic) NSNumber* Z;

@property(nonatomic) NSNumber* width;

@property(nonatomic) NSNumber* height;

@property(nonatomic) NSString* behavior;

@property(nonatomic) NSNumber* composition;

@property(nonatomic) NSNumber* fakeTargetId;

@property(nonatomic) NSString* text;

@property(nonatomic) NSString* value;

@property(nonatomic) NSString* style;

@property(nonatomic) NSString* autoplay;

@property(nonatomic) NSString* show;

@property(nonatomic) NSString* ref;

@end
