#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGTest.h"


@protocol SWGSubcourse
@end

@interface SWGSubcourse : SWGObject


@property(nonatomic) NSString* name;
/* URL indicating where the pdf document for this subcourse can be found 
 */
@property(nonatomic) NSString* document;

@property(nonatomic) NSArray<SWGTest>* tests;

@end
